version: '3'
services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      PG_URI: ${PG_URI}
    command: npm run serve
  db:
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}
